version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.10
    commands:
      - echo "Installing dependencies"
      - pip install --upgrade pip
      - pip install -r requirements.txt

  pre_build:
    commands:
      - echo "Running lint checks"
      - pylint *.py || true

  build:
    commands:
      - echo "Running tests"
      - pytest

artifacts:
  files:
    - "**/*"
